global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'vmagent'
    static_configs:
      - targets: ['vmagent:8429']
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']
  - job_name: 'node'
    static_configs:
      - targets:
        - dppo-osa-ansi-dev.dmz.test.ot:9100 # Main VictoriaMetrics VM and node exporter on it
        - cbr-lot1-oscp-m.dmz.test.ot:9100
        - cbr-lot1-oscp-n1.dmz.test.ot:9100
        - cbr-lot1-oscp-n2.dmz.test.ot:9100
        - cbr-lot1-oscp-in1.dmz.test.ot:9100
        - cbr-lot1-oscp-in2.dmz.test.ot:9100
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets:
        - cadvisor:8080
